// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Apply: typeof import('./src/components/apply/Apply.vue')['default']
    Article: typeof import('./src/components/article/Article.vue')['default']
    ArticleCommentList: typeof import('./src/components/article/ArticleCommentList.vue')['default']
    ArticleCommentListItem: typeof import('./src/components/article/ArticleCommentListItem.vue')['default']
    ArticleContent: typeof import('./src/components/article/ArticleContent.vue')['default']
    BackToTop: typeof import('./src/components/common/BackToTop.vue')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    Course: typeof import('./src/components/course/Course.vue')['default']
    CourseCategory: typeof import('./src/components/course/CourseCategory.vue')['default']
    CourseHead: typeof import('./src/components/course/CourseHead.vue')['default']
    CourseIntroduce: typeof import('./src/components/course/CourseIntroduce.vue')['default']
    CourseList: typeof import('./src/components/courseList/CourseList.vue')['default']
    CourseListHead: typeof import('./src/components/courseList/CourseListHead.vue')['default']
    CourseListItem: typeof import('./src/components/courseList/CourseListItem.vue')['default']
    Divider: typeof import('./src/components/common/Divider.vue')['default']
    FullScreenButton: typeof import('./src/components/common/FullScreenButton.vue')['default']
    Mode: typeof import('./src/components/common/Mode/index.vue')['default']
    ModePicker: typeof import('./src/components/common/ModePicker.vue')['default']
    NavBar: typeof import('./src/components/common/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/common/SearchBox.vue')['default']
    SWPopup: typeof import('./src/components/pwa/SWPopup.vue')['default']
    Tag: typeof import('./src/components/common/Tag.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
